MT#15463 implement check config
Change-Id: Ia8737095a2747dca2d39162a6efe4d937c4d5c47

diff --git a/debian/ngcp-rate-o-mat.init b/debian/ngcp-rate-o-mat.init
--- a/debian/ngcp-rate-o-mat.init
+++ b/debian/ngcp-rate-o-mat.init
@@ -41,6 +41,15 @@ fi
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
+
+do_check()
+{
+	if ! ${DAEMON} -c ; then
+		log_daemon_msg "check config failed"
+		exit 0
+	fi
+}
+
 #
 # Function that starts the daemon/service
 #
@@ -64,6 +73,8 @@ do_start()
 	      ;;
 	  esac
 	fi
+
+	do_check
 
 	# Return
 	#   0 if daemon has been started
